package com.gsx.googleadcompose.error;

public enum AdmErrorType {
    LIST_AD_ID_IS_EMPTY,
    LOAD_TIME_LESS_THEN_N_HOURS_AGO,
    AD_IS_LOADING,
    AD_ID_IS_NOT_EXIST,
    NETWORK_IS_NOT_AVAILABLE,
    AD_IS_EXISTED,
    AD_IS_NOT_AVAILABLE,
    CLIENT_HAVE_SUB,
    ACTIVITY_IS_NOT_AVAILABLE,
    CLIENT_HAVE_BEEN_REMOVED_AD,
    UMP_IS_NOT_ACTIVE,
    OTHER
}
